const applications = [
  {
    app_id: 1,
    company: "Amazon",
    position: "Software Enginner",
    status: "Applied",
    date: 1708556209,
    note: "Hello, Amazon",
    job_description_link: "https://www.amazon.ca",
  },
  {
    app_id: 2,
    company: "Google",
    position: "Front End Developer",
    status: "Rejected",
    date: 1708556209,
    note: "Hello, Google",
    job_description_link: "https://www.google.com/",
  },
  {
    app_id: 3,
    company: "Meta",
    position: "Backend Developer",
    status: "Interviewing",
    date: 1708556209,
    note: "Hello, Meta",
    job_description_link: "https://about.meta.com/metaverse/",
  },
  {
    app_id: 3,
    company: "LinkedIn",
    position: "Full Stack Developer",
    status: "Offer",
    date: 1708556209,
    note: "Hello, LinkedIn",
    job_description_link: "https://www.linkedin.com",
  },
];
