export const applications = [
  {
    app_id: 1,
    company: "Amazon Amazon Ama A Vjhkjdfghdjfhg",
    position: "Software Enginner",
    status: "interviewing",
    date: 1708556209,
    note: "Hello, Amazon",
    job_description_link: "https://www.amazon.ca",
  },
  {
    app_id: 2,
    company: "Google",
    position: "Front End Developer",
    status: "applied",
    date: 1708556209,
    note: "Hello, Google",
    job_description_link: "https://www.google.com/",
  },
  {
    app_id: 3,
    company: "Meta",
    position: "Backend Developer",
    status: "applied",
    date: 1708556209,
    note: "Hello, Meta",
    job_description_link: "https://about.meta.com/metaverse/",
  },
  {
    app_id: 4,
    company: "LinkedIn",
    position: "Full Stack Developer",
    status: "offer",
    date: 1708556209,
    note: "Hello, LinkedIn",
    job_description_link: "https://www.linkedin.com",
  },
  {
    app_id: 5,
    company: "Intergalactic Inc",
    position: "Software Engineer",
    status: "rejected",
    date: 1708556209,
    note: "Hello, Intergalactic. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    job_description_link: "https://intergalactic.com/",
  },
];
