// export const applications = [
//   {
//     id: "1",
//     company: "Amazon Amazon Ama A Vjhkjdfghdjfhg",
//     position: "Software Enginner",
//     status: "INTERVIEWING",
//     date: "1709163107",
//     note: "Hello, Amazon",
//     jobDescriptionLink: "https://www.amazon.ca",
//   },
//   {
//     id: "2",
//     company: "Google",
//     position: "Front End Developer",
//     status: "APPLIED",
//     date: "1709163107",
//     note: "Hello, Google",
//     jobDescriptionLink: "https://www.google.com/",
//   },
//   {
//     id: "3",
//     company: "Meta",
//     position: "Backend Developer",
//     status: "APPLIED",
//     date: "1709163107",
//     note: "Hello, Meta",
//     jobDescriptionLink: "https://about.meta.com/metaverse/",
//   },
//   {
//     id: "4",
//     company: "LinkedIn",
//     position: "Full Stack Developer",
//     status: "OFFER",
//     date: "1709163107",
//     note: "Hello, LinkedIn",
//     jobDescriptionLink: "https://www.linkedin.com",
//   },
//   {
//     id: "5",
//     company: "Intergalactic Inc",
//     position: "Software Engineer",
//     status: "REJECTED",
//     date: "1709163107",
//     note: "Hello, Intergalactic. Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
//     jobDescriptionLink: "https://intergalactic.com/",
//   },
// ];
